edition = "2021"
version = "Two"
imports_layout = "Vertical"
fn_params_layout = "Vertical"
newline_style = "Unix"
group_imports = "StdExternalCrate"
imports_granularity = "Module"
use_try_shorthand = true
wrap_comments = true
max_width = 100
comment_width = 100
