apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "netcheck.fullname" . }}
  labels:
    {{- include "netcheck.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "netcheck.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "netcheck.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "netcheck.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          args:
            - --verbose={{ .Values.verbose }}
            - --log-level={{ .Values.logLevel }}
            - --timeout-ms={{ .Values.timeoutMs }}
            - --wait-time-seconds={{ .Values.waitTimeSeconds }}
            - --connect-timeout-ms={{ .Values.connectTimeoutMs }}
            - --failure-threshold={{ .Values.failureThreshold }}
            - --metrics_port={{ .Values.service.metrics_port }}
            {{- with .Values.targets }}
            {{- range . }}
            - --target="{{ .name }}={{ .urls | join "," }}"
            {{- end }}
            {{- end }}
          ports:
            - name: metrics
              containerPort: {{ .Values.service.metrics_port }}
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: metrics
          readinessProbe:
            httpGet:
              path: /
              port: metrics
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
