apiVersion: v1
kind: Service
metadata:
  name: {{ include "netcheck.fullname" . }}
  labels:
    {{- include "netcheck.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.metrics_port }}
      targetPort: {{ .Values.service.metrics_port }}
      protocol: TCP
      name: metrics
  selector:
    {{- include "netcheck.selectorLabels" . | nindent 4 }}
