name: pr-open

on:
  pull_request_target:
    types: [ opened, reopened, synchronize ]

jobs:
  labels:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    steps:
      - uses: actions/labeler@v4
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          configuration-path: .github/labels.yaml
